import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Search } from 'lucide-react';
export function DeveloperFilters({ filters, onFilterChange, onSearch, isLoading, }) {
    const handleInputChange = (key, value) => {
        onFilterChange({
            ...filters,
            [key]: value || undefined,
        });
    };
    return (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-lg", children: "Search Filters" }) }), _jsxs(CardContent, { className: "space-y-4", children: [_jsxs("div", { children: [_jsx(Label, { htmlFor: "language", children: "Programming Language" }), _jsx(Input, { id: "language", placeholder: "e.g. Python, JavaScript, Go", value: filters.language || '', onChange: e => handleInputChange('language', e.target.value), className: "mt-1" })] }), _jsxs("div", { children: [_jsx(Label, { htmlFor: "location", children: "Location" }), _jsx(Input, { id: "location", placeholder: "e.g. San Francisco, Remote", value: filters.location || '', onChange: e => handleInputChange('location', e.target.value), className: "mt-1" })] }), _jsxs("div", { children: [_jsx(Label, { htmlFor: "email_domain", children: "Email Domain" }), _jsx(Input, { id: "email_domain", placeholder: "e.g. gmail.com, company.com", value: filters.email_domain || '', onChange: e => handleInputChange('email_domain', e.target.value), className: "mt-1" })] }), _jsxs("div", { className: "grid grid-cols-2 gap-3", children: [_jsxs("div", { children: [_jsx(Label, { htmlFor: "min_followers", children: "Min Followers" }), _jsx(Input, { id: "min_followers", type: "number", min: "0", placeholder: "0", value: filters.min_followers || '', onChange: e => handleInputChange('min_followers', parseInt(e.target.value) || 0), className: "mt-1" })] }), _jsxs("div", { children: [_jsx(Label, { htmlFor: "max_followers", children: "Max Followers" }), _jsx(Input, { id: "max_followers", type: "number", min: "0", placeholder: "10000", value: filters.max_followers || '', onChange: e => handleInputChange('max_followers', parseInt(e.target.value) || undefined), className: "mt-1" })] })] }), _jsxs("div", { children: [_jsx(Label, { htmlFor: "sort_by", children: "Sort By" }), _jsxs("select", { id: "sort_by", value: filters.sort_by || 'devrank', onChange: e => handleInputChange('sort_by', e.target.value), className: "w-full mt-1 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", children: [_jsx("option", { value: "devrank", children: "DevRank Score" }), _jsx("option", { value: "followers", children: "Followers" }), _jsx("option", { value: "stars", children: "Stars" }), _jsx("option", { value: "recent", children: "Recently Active" })] })] }), _jsxs(Button, { onClick: onSearch, className: "w-full", disabled: isLoading, children: [_jsx(Search, { className: "mr-2", size: 16 }), isLoading ? 'Searching...' : 'Search Developers'] })] })] }));
}
