import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { useCandidateStore } from '@/store/useCandidateStore';
import { Users, BookOpen, Heart, Github } from 'lucide-react';
export default function NavigationBar() {
    const location = useLocation();
    const { candidates } = useCandidateStore();
    const isActive = (path) => location.pathname === path;
    return (_jsx("nav", { className: "border-b bg-background sticky top-0 z-50", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 md:px-8", children: _jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs(Link, { to: "/developers", className: "flex items-center gap-2 mr-8", children: [_jsx("div", { className: "h-8 w-8 rounded-lg bg-primary flex items-center justify-center", children: _jsx(Github, { className: "text-primary-foreground", size: 20 }) }), _jsx("span", { className: "font-bold text-lg hidden sm:inline", children: "BountyLab Recruiter" })] }), _jsxs("div", { className: "flex items-center gap-1 flex-1 md:flex-none md:gap-2", children: [_jsx(Link, { to: "/developers", children: _jsxs(Button, { variant: isActive('/developers') ? 'default' : 'ghost', size: "sm", className: "gap-2", children: [_jsx(Users, { size: 18 }), _jsx("span", { className: "hidden sm:inline", children: "Developers" })] }) }), _jsx(Link, { to: "/repos", children: _jsxs(Button, { variant: isActive('/repos') ? 'default' : 'ghost', size: "sm", className: "gap-2", children: [_jsx(BookOpen, { size: 18 }), _jsx("span", { className: "hidden sm:inline", children: "Repositories" })] }) }), _jsx(Link, { to: "/candidates", children: _jsxs(Button, { variant: isActive('/candidates') ? 'default' : 'ghost', size: "sm", className: "gap-2", children: [_jsx(Heart, { size: 18 }), _jsx("span", { className: "hidden sm:inline", children: "Candidates" }), candidates.length > 0 && (_jsx("span", { className: "bg-primary text-primary-foreground rounded-full h-5 w-5 text-xs flex items-center justify-center", children: candidates.length }))] }) })] }), _jsx(Button, { asChild: true, variant: "ghost", size: "icon", children: _jsx("a", { href: "https://github.com", target: "_blank", rel: "noopener noreferrer", title: "GitHub", children: _jsx(Github, { size: 20 }) }) })] }) }) }));
}
